app/Http/routes.php
<?php

/*
 * This file is part of Bootstrap CMS.
 *
 * (c) Graham Campbell <graham@alt-three.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// send users to the home page
$router->get('/', ['as' => 'base', function () {
    Session::flash('', ''); // work around laravel bug if there is no session yet
    Session::reflash();

    return Redirect::to('pages/home');
}]);

// send users to the posts page
if (Config::get('cms.blogging')) {
    $router->get('blog', ['as' => 'blog', function () {
        Session::flash('', ''); // work around laravel bug if there is no session yet
        Session::reflash();

        return Redirect::route('blog.posts.index');
    }]);
}

// page routes
$router->resource('pages', 'PageController');

// blog routes
if (Config::get('cms.blogging')) {
    $router->resource('blog/posts', 'PostController');
    $router->resource('blog/posts.comments', 'CommentController');
}

// event routes
if (Config::get('cms.events')) {
    $router->resource('events', 'EventController');
}

resources/views/pages/create.blade.php
@extends('layouts.default')

@section('title')
Create Page
@stop

@section('top')
<div class="page-header">
<h1>Create Page</h1>
</div>
@stop

@section('content')
<div class="well">
    <?php
    $form = ['url' => URL::route('pages.store'),
        'method' => 'POST',
        'button' => 'Create New Page',
        'defaults' => [
            'title' => '',
            'nav_title' => '',
            'slug' => '',
            'icon' => '',
            'body' => '',
            'css' => '',
            'js' => '',
            'show_title' => true,
            'show_nav' => true,
    ], ];
    ?>
    @include('pages.form')
</div>
@stop

@section('css')
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.min.css">
@stop

@section('js')
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    $(".make-switch").bootstrapSwitch();
    var title = $('#title');
    title.keyup(function (e) {
        val = title.val();
        $("#nav_title").val(val);
        var slug = val.replace(/[^a-zA-Z0-9\s]/g, '')
                 .replace(/^\s+|\s+$/, '')
                 .replace(/\s+/g, '-')
                 .toLowerCase();
        $("#slug").val(slug);
    });
});
</script>
@stop

resources/views/pages/delete.blade.php
<div id="delete_page" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Are you sure?</h4>
            </div>
            <div class="modal-body">
                <p>You are about to delete this page! This process cannot be undone.</p>
                <p>Are you sure you wish to continue?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-success" href="{!! URL::route('pages.destroy', array('pages' => $page->slug)) !!}" data-token="{!! Session::getToken() !!}" data-method="DELETE">Yes</a>
                <button class="btn btn-danger" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

resources/views/pages/edit.blade.php
@extends('layouts.default')

@section('title')
Edit {{ $page->title }}
@stop

@section('top')
<div class="page-header">
<h1>Edit {{ $page->title }}</h1>
</div>
@stop

@section('content')
<div class="row">
    <div class="col-xs-6">
        <p class="lead">
            Please edit the page:
        </p>
    </div>
    <div class="col-xs-6">
        <div class="pull-right">
            <a class="btn btn-success" href="{!! URL::route('pages.show', array('pages' => $page->slug)) !!}"><i class="fa fa-file-text"></i> Show Page</a> <a class="btn btn-danger" href="#delete_page" data-toggle="modal" data-target="#delete_page"><i class="fa fa-times"></i> Delete Page</a>
        </div>
    </div>
</div>
<hr>
<div class="well">
    <?php
    $form = ['url' => URL::route('pages.update', ['pages' => $page->slug]),
        '_method' => 'PATCH',
        'method' => 'POST',
        'button' => 'Save Page',
        'defaults' => [
            'title' => $page->title,
            'nav_title' => $page->nav_title,
            'slug' => $page->slug,
            'icon' => $page->icon,
            'body' => $page->body,
            'css' => $page->css,
            'js' => $page->js,
            'show_title' => ($page->show_title == true),
            'show_nav' => ($page->show_nav == true),
    ], ];
    ?>
    @include('pages.form')
</div>
@stop

@section('bottom')
@auth('edit')
    @include('pages.delete')
@endauth
@stop

@section('css')
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.min.css">
@stop

@section('js')
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    $(".make-switch").bootstrapSwitch();
});
</script>
@stop

resources/views/pages/form.blade.php
<form class="form-horizontal" action="{{ $form['url'] }}" method="{{ $form['method'] }}">

    {{ csrf_field() }}
    <input type="hidden" name="_method" value="{{ isset($form['_method'])? $form['_method'] : $form['method'] }}">

    <div class="form-group{!! ($errors->has('title')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="title">Page Title</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input name="title" id="title" value="{!! Request::old('title', $form['defaults']['title']) !!}" type="text" class="form-control" placeholder="Page Title">
            {!! ($errors->has('title') ? $errors->first('title') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('nav_title')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="nav_title">Page Nav Title</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input name="nav_title" id="nav_title" value="{!! Request::old('nav_title', $form['defaults']['nav_title']) !!}" type="text" class="form-control" placeholder="Page Nav Title">
            {!! ($errors->has('nav_title') ? $errors->first('nav_title') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('slug')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="slug">Page Slug</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input name="slug" id="slug" value="{!! Request::old('slug', $form['defaults']['slug']) !!}" type="text" class="form-control" placeholder="Page Slug">
            {!! ($errors->has('slug') ? $errors->first('slug') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('icon')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="icon">Page Icon</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input name="icon" id="icon" value="{!! Request::old('icon', $form['defaults']['icon']) !!}" type="text" class="form-control" placeholder="Page Icon">
            {!! ($errors->has('icon') ? ' '.$errors->first('icon') : '(optional)') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('body')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="body">Page Body</label>
        <div class="col-lg-6 col-md-8 col-sm-9 col-xs-12">
            <textarea name="body" id="body" class="form-control" placeholder="Page Body" rows="8">{!! Request::old('body', $form['defaults']['body']) !!}</textarea>
            {!! ($errors->has('body') ? $errors->first('body') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('css')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="css">Page CSS</label>
        <div class="col-lg-6 col-md-8 col-sm-9 col-xs-12">
            <textarea name="css" id="css" class="form-control" placeholder="Page CSS" rows="8">{!! Request::old('css', $form['defaults']['css']) !!}</textarea>
            {!! ($errors->has('css') ? $errors->first('css') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('js')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="js">Page JS</label>
        <div class="col-lg-6 col-md-8 col-sm-9 col-xs-12">
            <textarea name="js" id="js" class="form-control" placeholder="Page JS" rows="8">{!! Request::old('js', $form['defaults']['js']) !!}</textarea>
            {!! ($errors->has('js') ? $errors->first('js') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('show_title')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="show_title">Show Title</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input class="make-switch" data-on-text="<i class='fa fa-check fa-inverse'></i>" data-off-text="<i class='fa fa-times'>" name="show_title" id="show_title" type="checkbox"{!! (Request::old('show_title', $form['defaults']['show_title']) == true) ? ' checked' : '' !!}>
            {!! ($errors->has('show_title') ? $errors->first('show_title') : '') !!}
        </div>
    </div>

    <div class="form-group{!! ($errors->has('show_nav')) ? ' has-error' : '' !!}">
        <label class="col-md-2 col-sm-3 col-xs-10 control-label" for="show_nav">Show On Nav</label>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-10">
            <input class="make-switch" data-on-text="<i class='fa fa-check fa-inverse'></i>" data-off-text="<i class='fa fa-times'>" name="show_nav" id="show_nav" type="checkbox"{!! (Request::old('show_nav', $form['defaults']['show_nav']) == true) ? ' checked' : '' !!}>
            {!! ($errors->has('show_nav') ? $errors->first('show_nav') : '') !!}
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-sm-offset-3 col-sm-10 col-xs-12">
            <button class="btn btn-primary" type="submit"><i class="fa fa-rocket"></i> {!! $form['button'] !!}</button>
        </div>
    </div>

</form>

resources/views/pages/show.blade.php
@extends('layouts.default')

@section('title')
{{ $page->title }}
@stop

@section('top')
@if($page->show_title)
    <div class="page-header">
    <h1>{{ $page->title }}</h1>
    </div>
@endif
@stop

@section('content')
@auth('edit')
    <div class="well clearfix">
        <div class="hidden-xs">
            <div class="col-xs-6">
                <p>
                    <strong>Page Owner:</strong> {!! $page->owner !!}
                </p>
                <a class="btn btn-info" href="{!! URL::route('pages.edit', array('pages' => $page->slug)) !!}"><i class="fa fa-pencil-square-o"></i> Edit Page</a> <a class="btn btn-danger" href="#delete_page" data-toggle="modal" data-target="#delete_page"><i class="fa fa-times"></i> Delete Page</a>
            </div>
            <div class="col-xs-6">
                <div class="pull-right">
                    <p>
                        <em>Page Created: {!! html_ago($page->created_at) !!}</em>
                    </p>
                    <p>
                        <em>Last Updated: {!! html_ago($page->updated_at) !!}</em>
                    </p>
                </div>
            </div>
        </div>
        <div class="visible-xs">
            <div class="col-xs-12">
                <p>
                    <strong>Page Owner:</strong> {!! $page->owner !!}
                </p>
                <p>
                    <strong>Page Created:</strong> {!! html_ago($page->created_at) !!}
                </p>
                <p>
                    <strong>Last Updated:</strong> {!! html_ago($page->updated_at) !!}
                </p>
                <a class="btn btn-info" href="{!! URL::route('pages.edit', array('pages' => $page->slug)) !!}"><i class="fa fa-pencil-square-o"></i> Edit Page</a> <a class="btn btn-danger" href="#delete_page" data-toggle="modal" data-target="#delete_page"><i class="fa fa-times"></i> Delete Page</a>
            </div>
        </div>
    </div>
    <hr>
@endauth
@if (Config::get('cms.eval', false))
<?php eval('?>'.$page->body); ?>
@else
{!! $page->body !!}
@endif
@stop

@section('bottom')
@auth('edit')
    @include('pages.delete')
@endauth
@stop

@section('css')
{!! $page->css !!}
@stop

@section('js')
{!! $page->js !!}
@stop